version: '2'

services:
  web:
    image: agaveapi/httpd:2.4
    hostname: togo.staging.agaveapi.co
    restart: on-failure
    environment:
      - 'DOCUMENT_ROOT=/var/www/html'
      - 'LOG_TARGET_STDOUT=1'
    ports:
      - '80:80'
    volumes:
      - '.:/var/www/html:ro'
    labels:
      - "traefik.backend=togo"
      - "traefik.frontend.rule=Host:togo.staging.agaveapi.co"
      - "traefik.port=80"
      - "traefik.protocol=http"
      - "traefik.frontend.entryPoints=https,http"
    networks:
      - togo

networks:
  togo: